defaults:
  - override hydra/launcher: submitit_slurm

hparams:
  device: "cuda"

  tokenizer_model: "microsoft/phi-1_5"
  model: "../models/finetuned/phi/"
  checkpoint: "checkpoint-625"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  max_length: 200
  batch_size_inference: 256
  full_eval: False

  unlearning: True
  unlearning_loss: "pmc"
  pmc_selection: "rouge_reward"

  lambda: 1.5
  top_p: 0.95
  temperature: 1.25
  num_samples: 5
  num_epochs: 40
  min_len: 0

  batch_size: 16
  gradient_accumulation_steps: 4
  learning_rate: 1e-5
  weight_decay: 0.01
  gradient_checkpointing: False

  save_model: True
  seed: 0
  split: 10
  logging: False

hydra:  
  sweep:
    dir: ../models/unlearned/phi/${hparams.seed}/
    subdir: . 

  launcher:
    submitit_folder: ../models/unlearned/phi/submitit
    timeout_min: 60
    gres: gpu:1
    mem_gb: 40
    partition: gpu_h100
    qos: default
    cpus_per_task: 1
    tasks_per_node: 1
    name: PMC-phi
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    signal_delay_s: 0
    max_num_timeout: 0